# Generated by Django 4.2.2 on 2023-06-30 01:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("boards", "0002_boards"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="boards",
            options={"permissions": (("es_miembro_1", "Es miembro con prioridad 1"),)},
        ),
    ]
